# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    # Configuration du stockage des sessions en base via PdoSessionHandler
    session:
        handler_id: session.handler.pdo
        cookie_secure: auto
        cookie_samesite: lax

# Service pour gérer la session en base MySQL
services:
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - '%env(resolve:DATABASE_URL)%'
            - { lock_mode: 0 }

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@dev:
    imports:
        - { resource: debug.yaml }