# Fichier désactivé pour la production, car WebProfilerBundle n'est pas chargé
# (tout le contenu est commenté)

# when@dev:
#     web_profiler_wdt:
#         resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
#         prefix: /_wdt

#     web_profiler_profiler:
#         resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
#         prefix: /_profiler
